export const ALL_PRODUCTNEW_REQUEST = "ALL_PRODUCTNEW_REQUEST";
export const ALL_PRODUCTNEW_SUCCESS = "ALL_PRODUCTNEW_SUCCESS";
export const ALL_PRODUCTNEW_FAIL = "ALL_PRODUCTNEW_FAIL";

export const ADMIN_PRODUCTNEW_REQUEST = "ADMIN_PRODUCTNEW_REQUEST";
export const ADMIN_PRODUCTNEW_SUCCESS = "ADMIN_PRODUCTNEW_SUCCESS";
export const ADMIN_PRODUCTNEW_FAIL = "ADMIN_PRODUCTNEW_FAIL";

export const NEW_PRODUCTNEW_REQUEST = "NEW_PRODUCTNEW_REQUEST";
export const NEW_PRODUCTNEW_SUCCESS = "NEW_PRODUCTNEW_SUCCESS";
export const NEW_PRODUCTNEW_RESET = "NEW_PRODUCTNEW_RESET";
export const NEW_PRODUCTNEW_FAIL = "NEW_PRODUCTNEW_FAIL";

export const UPDATE_PRODUCTNEW_REQUEST = "UPDATE_PRODUCTNEW_REQUEST";
export const UPDATE_PRODUCTNEW_SUCCESS = "UPDATE_PRODUCTNEW_SUCCESS";
export const UPDATE_PRODUCTNEW_RESET = "UPDATE_PRODUCTNEW_RESET";
export const UPDATE_PRODUCTNEW_FAIL = "UPDATE_PRODUCTNEW_FAIL";

export const DELETE_PRODUCTNEW_REQUEST = "DELETE_PRODUCTNEW_REQUEST";
export const DELETE_PRODUCTNEW_SUCCESS = "DELETE_PRODUCTNEW_SUCCESS";
export const DELETE_PRODUCTNEW_RESET = "DELETE_PRODUCTNEW_RESET";
export const DELETE_PRODUCTNEW_FAIL = "DELETE_PRODUCTNEW_FAIL";

export const PRODUCTNEW_DETAILS_REQUEST = "PRODUCTNEW_DETAILS_REQUEST";
export const PRODUCTNEW_DETAILS_SUCCESS = "PRODUCTNEW_DETAILS_SUCCESS";
export const PRODUCTNEW_DETAILS_FAIL = "PRODUCTNEW_DETAILS_FAIL";

export const NEW_REVIEWNEW_REQUEST = "NEW_REVIEWNEW_REQUEST";
export const NEW_REVIEWNEW_SUCCESS = "NEW_REVIEWNEW_SUCCESS";
export const NEW_REVIEWNEW_RESET = "NEW_REVIEWNEW_RESET";
export const NEW_REVIEWNEW_FAIL = "NEW_REVIEWNEW_FAIL";

export const ALL_REVIEWNEW_REQUEST = "ALL_REVIEWNEW_REQUEST";
export const ALL_REVIEWNEW_SUCCESS = "ALL_REVIEWNEW_SUCCESS";
export const ALL_REVIEWNEW_FAIL = "ALL_REVIEWNEW_FAIL";

export const DELETE_REVIEWNEW_REQUEST = "DELETE_REVIEWNEW_REQUEST";
export const DELETE_REVIEWNEW_SUCCESS = "DELETE_REVIEWNEW_SUCCESS";
export const DELETE_REVIEWNEW_RESET = "DELETE_REVIEWNEW_RESET";
export const DELETE_REVIEWNEW_FAIL = "DELETE_REVIEWNEW_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
